'use strict';

export const IMPORT_DATA = 'IMPORT_DATA';

export const CREATE_SPRINT = 'CREATE_SPRINT';
export const DELETE_SPRINT = 'DELETE_SPRINT';

export const SET_SPRINT_ID = 'SET_SPRINT_ID';
export const SET_SPRINT_STARTDATE = 'SET_SPRINT_STARTDATE';
export const SET_SPRINT_WEEKHOURS = 'SET_SPRINT_WEEKHOURS';
export const SET_SPRINT_WEEKS = 'SET_SPRINT_WEEKS';
export const SET_SPRINT_COMPLETED = 'SET_SPRINT_COMPLETED';
export const UPDATE_SPRINT_ENDDATE = 'UPDATE_SPRINT_ENDDATE';

export const ADD_SPRINT_MEMBER = 'ADD_SPRINT_MEMBER';
export const REMOVE_SPRINT_MEMBER = 'REMOTE_SPRINT_MEMBER';

export const ADD_SPRINT_ABSENCE = 'ADD_SPRINT_ABSENCE';
export const REMOVE_SPRINT_ABSENCE = 'REMOVE_SPRINT_ABSENCE';
